// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ80ZkkZR6NjEneKxiFYoCHrRVYJlZU_g',
    appId: '1:622660104571:web:7c4ed583f122e7a9d8cdde',
    messagingSenderId: '622660104571',
    projectId: 'attune-6767',
    authDomain: 'attune-6767.firebaseapp.com',
    storageBucket: 'attune-6767.firebasestorage.app',
    measurementId: 'G-PL8V8PZMML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcXc1w6yTdP1notAzHgRYCT6clE3F3ZVE',
    appId: '1:622660104571:android:1f0bafeaf56c60a8d8cdde',
    messagingSenderId: '622660104571',
    projectId: 'attune-6767',
    storageBucket: 'attune-6767.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAAMPEBr1hkKj7-mpY5622hWFln9hpMgU',
    appId: '1:622660104571:ios:9e7b984417f48da5d8cdde',
    messagingSenderId: '622660104571',
    projectId: 'attune-6767',
    storageBucket: 'attune-6767.firebasestorage.app',
    iosBundleId: 'com.example.attune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAAMPEBr1hkKj7-mpY5622hWFln9hpMgU',
    appId: '1:622660104571:ios:9e7b984417f48da5d8cdde',
    messagingSenderId: '622660104571',
    projectId: 'attune-6767',
    storageBucket: 'attune-6767.firebasestorage.app',
    iosBundleId: 'com.example.attune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ80ZkkZR6NjEneKxiFYoCHrRVYJlZU_g',
    appId: '1:622660104571:web:317c0cbe091691f5d8cdde',
    messagingSenderId: '622660104571',
    projectId: 'attune-6767',
    authDomain: 'attune-6767.firebaseapp.com',
    storageBucket: 'attune-6767.firebasestorage.app',
    measurementId: 'G-8EWPPBLNK4',
  );
}