import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model.dart';

// Talks to Firebase Auth (to sign up/in/out)
// handles Firebase Authentication and Firestore user doc creation. 
// Nothing should call this except AuthProvider I'm pretty sure
class AuthService {

  // handles login/signup
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // reads/writes user docs since firebase only stores user's email and password
  // but we store more than that (username, topGenres, etc)
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // This is a stream that listens to auth state changes. 
  // Lets the app automatically know when someone logs in or out
  Stream<User?> get authStateChanges => _auth.authStateChanges();

  // this updates the user's location when they enable permissions
  // user is identified through their firebase-given uid
  Future<void> updateLocation(String uid, double lat, double long) async {
    await _db.collection('users').doc(uid).update({
      'latitude': lat,
      'longitude': long,
    });
  }

  // getter for the current user
  Future<User?> getCurrentUser() async {
    return _auth.currentUser;
  }

  // self explanatory
  // async bc its making a network call
  Future<UserModel> signUp({
    required String username,
    required String password,
    required String email,
    String university = '',
    List<String> topGenres = const [],
    String? spotifyId,
    }) async {
      // call firebase to complete the acc - cred is Firebase's response after creating new account
      final cred = await _auth.createUserWithEmailAndPassword( 
        email: email, 
        password: password,
      );

    // create the UserModel
    // getting uid from firebase -> cred -> .user (user object) 
    // -> .uid (actual uid string generated by Firebase for this user)
    final newUser = UserModel(
      uid: cred.user!.uid, 
      username: username, 
      email: email, 
      topGenres: topGenres, 
      spotifyId: spotifyId,
      );

    // save new user to Firestore 
    // gets newUser from collection, find or create user doc with this user's id, then  
    // writes the map data into that doc
    await _db.collection('users').doc(newUser.uid).set(newUser.toMap());

    return newUser;
  }

  // self explanatory
  // async bc its making a network call
  Future<void> signIn({required String email, required String password}) async {

    // AuthProvider will get the user via the auth state stream
    await _auth.signInWithEmailAndPassword(email: email, password: password);
  }

  // creates user so that firebase saves info so you can actually log in
  Future<void> createUser(UserModel user) async {
    await _db.collection('users').doc(user.uid).set(user.toMap());
  }

  // self explanatory
  // async bc its making a network call
  Future<void> signOut() async {
    await _auth.signOut();
  }

  // goes to Firestore and returns the UserModel for the given uid
  Future<UserModel?> fetchUser(String uid) async {
    final doc = await _db.collection('users').doc(uid).get();
    
    // if the user doesnt exist, return null
    if (!doc.exists) {
      return null;
    } 
    // otherwise, return the user as a UserModel
    else {
      return UserModel.fromMap(uid, doc.data()!);
    }
    
  }

  // updates the user's Spotify ID and top genres.
  // called after a successful Spotify login
  Future<void> updateSpotifyData({
    required String uid,
    required String spotifyId,
    required List<String> topGenres,
  }) async {
    await _db.collection('users').doc(uid).update({
      'spotifyId': spotifyId,
      'topGenres': topGenres,
    });
  }

  // updates the user's profile picture URL in firestore
  Future<void> updatePfp({
    required String uid,
    required String pfp,
  }) async {
    await _db.collection('users').doc(uid).update({
      'pfp': pfp,
    });
  }
}