import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/user_model.dart';
import 'dart:math';

// Talks to Firebase Auth (to sign up/in/out)
// handles Firebase Authentication and Firestore user doc creation.
// Nothing should call this except AuthProvider I'm pretty sure
class AuthService {
  // handles login/signup
  final FirebaseAuth _auth = FirebaseAuth.instance;

  // reads/writes user docs since firebase only stores user's email and password
  // but we store more than that (username, topGenres, etc)
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // This is a stream that listens to auth state changes.
  // Lets the app automatically know when someone logs in or out
  Stream<User?> get authStateChanges => _auth.authStateChanges();

  // this updates the user's location when they enable permissions
  // user is identified through their firebase-given uid
  Future<void> updateLocation(String uid, double lat, double long) async {
    await _db.collection('users').doc(uid).update({
      'latitude': lat,
      'longitude': long,
    });
  }

  // getter for the current user
  Future<User?> getCurrentUser() async {
    return _auth.currentUser;
  }

  // self explanatory
  // async bc its making a network call
  Future<UserModel> signUp({
    required String username,
    required String password,
    required String email,
    String university = '',
    List<String> topGenres = const [],
    String? spotifyId,
  }) async {
    // call firebase to complete the acc - cred is Firebase's response after creating new account
    final cred = await _auth.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );

    // create the UserModel
    // getting uid from firebase -> cred -> .user (user object)
    // -> .uid (actual uid string generated by Firebase for this user)
    final newUser = UserModel(
      uid: cred.user!.uid,
      username: username,
      email: email,
      topGenres: topGenres,
      spotifyId: spotifyId,
    );

    // save new user to Firestore
    // gets newUser from collection, find or create user doc with this user's id, then
    // writes the map data into that doc
    await _db.collection('users').doc(newUser.uid).set(newUser.toMap());

    return newUser;
  }

  // self explanatory
  // async bc its making a network call
  Future<void> signIn({required String email, required String password}) async {
    // AuthProvider will get the user via the auth state stream
    await _auth.signInWithEmailAndPassword(email: email, password: password);
  }

  // creates user so that firebase saves info so you can actually log in
  Future<void> createUser(UserModel user) async {
    await _db.collection('users').doc(user.uid).set(user.toMap());
  }

  // self explanatory
  // async bc its making a network call
  Future<void> signOut() async {
    await _auth.signOut();
  }

  // goes to Firestore and returns the UserModel for the given uid
  Future<UserModel?> fetchUser(String uid) async {
    final doc = await _db.collection('users').doc(uid).get();
    // if the user doesnt exist, return null
    if (!doc.exists) {
      return null;
    }
    // otherwise, return the user as a UserModel
    else {
      return UserModel.fromMap(uid, doc.data()!);
    }
  }

  // updates the user's Spotify ID and top genres.
  // called after a successful Spotify login
  Future<void> updateSpotifyData({
    required String uid,
    required String spotifyId,
    required List<String> topGenres,
    required List<String> topArtists,
  }) async {
    await _db.collection('users').doc(uid).update({
      'spotifyId': spotifyId,
      'topGenres': topGenres,
      'topArtists': topArtists,
    });
  }

  // updates the user's profile picture URL in firestore
  Future<void> updatePfp({required String uid, required String pfp}) async {
    await _db.collection('users').doc(uid).update({'pfp': pfp});
  }

  // sends a friend request
  Future<void> sendFriendRequest({
    required String currentUid,
    required String targetUid,
  }) async {
    await _db.collection('users').doc(targetUid).update({
      'friendRequests': FieldValue.arrayUnion([currentUid]),
    });
  }

  // accepts a friend request
  Future<void> acceptFriendRequest({
    required String currentUid,
    required String requesterUid,
  }) async {
    await _db.collection('users').doc(currentUid).update({
      'friends': FieldValue.arrayUnion([requesterUid]),
      'friendRequests': FieldValue.arrayRemove([requesterUid]),
    });
    await _db.collection('users').doc(requesterUid).update({
      'friends': FieldValue.arrayUnion([currentUid]),
    });
  }

  // declines a friend request
  Future<void> declineFriendRequest({
    required String currentUid,
    required String requesterUid,
  }) async {
    await _db.collection('users').doc(currentUid).update({
      'friendRequests': FieldValue.arrayRemove([requesterUid]),
    });
  }

  // gets nearby users
  // fetches all users and filters to those within 20 miles using the haversine formula
  // haversine is standard formula for calculating distance between 2 GPS coords on a sphere
  Future<List<UserModel>> getNearbyUsers({
    required String currentUid,
    required double lat,
    required double long, 
    double radiusMiles = 20,
  }) async {
    // using firestore methods to query database to fetch users with non-null lat fields 
    //    -> they have location enabled
    final snapshot = await _db
      .collection('users')
      .where('latitude', isNull: false) 
      .get();

    // convert each Firestore doc we just fetched into UserModel object so we can access their data
    final allUsers = snapshot.docs
      .map((doc) => UserModel.fromMap(doc.id, doc.data()))
      .toList();

    // filter out current user from nearby list, redundant
    final notMe = allUsers.where((user) => user.uid != currentUid).toList();

    // filter out users without a location
    final hasLocation = notMe 
      .where((user) => user.latitude != null && user.longitude != null) 
      .toList();

    // filter to only users within a 20 mile (or whatever we pick) radius
    final nearby = hasLocation.where((user) => 
      // remember user lat and long might be null
      _distanceMiles(lat, long, user.latitude!, user.longitude!) <= radiusMiles)
      .toList();

    // finally return list of users that arent you & are within 20 miles of you
    return nearby;

    // shoutout dart list functions, or whatever you're called, I love you so much
  }

  // haversine formula - calculates distance between two lat and long points in miles
  // technically it returns the shortetst distance between two points; the current user
  // is the starting point and the user we're comparing them to is the destination point
  // I used someone else's code as a reference for this - see README.md
  double _distanceMiles(double lat1, double long1, double lat2, double long2) {
    const earthRadius = 3958.8; // earhth's radius in miles
    final dLat = _toRad(lat2 - lat1); // difference in lat
    final dLong = _toRad(long2 - long1); // difference in long

    // square the sine of half the latitude difference
    final sinLat = sin(dLat / 2) * sin(dLat / 2);

    // square the sine of half the longitude difference
    final sinLong = sin(dLong / 2) * sin(dLong / 2);

    // account for the longitude difference shrinking near the poles (woah science)
    // since long degrees are closer together the further you get from the equator
    final cosProduct = cos(_toRad(lat1)) * cos(_toRad(lat2));

    // smush it all together --> haversine formula
    final combine = sinLat + cosProduct * sinLong;

    // convert from ratio to miles --> final distance
    return earthRadius * 2 * atan2(sqrt(combine), sqrt(1 - combine));
  }

  // helper method that returns degrees converted to radians
  // using 3.141592653589793 for pi here
  double _toRad(double deg) => deg * (3.141592653589793 / 180);


}
