name: attune
description: "Find community at college through your music taste"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.3
  url_launcher: ^6.2.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # we might not end up needing this
